name: Notify SMTP

on:
  workflow_dispatch:
    inputs:
      STATUS_FILE_PATH:
        type: string
      CALLING_REPO:
        type: string
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check_sites_status_and_notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout notifme
        uses: actions/checkout@v3
        with:
          repository: muuvlabs-upptime/muuvlabs-notifme
          path: main

      - name: Checkout upptime
        uses: actions/checkout@v3
        with:
          repository: "muuvlabs-upptime/muuvlabs-upptime"
          path: upptime-repo

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start
        working-directory: ./main
        run: |
          npm ci
          npm run start
        env:
          STATUS_FILE_PATH: ../../upptime-repo/history/summary.json
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
