name: Notify SMTP

on:
  workflow_dispatch:
    inputs:
      STATUS_FILE_PATH:
        type: string
      CALLING_REPO:
        type: string
  workflow_call:
    inputs:
      STATUS_FILE_PATH:
        required: true
        type: string
      CALLING_REPO:
        required: true
        type: string
    secrets:
      SMTP_HOST:
        required: true
      SMTP_PORT:
        required: true
      SMTP_SECURE:
        required: true
      SMTP_USER:
        required: true
      SMTP_PASS:
        required: true
      SMTP_FROM:
        required: true
      SMTP_TO:
        required: true
  schedule:
    - cron: "*/5 * * * *"

env:
  CALLING_REPO: ${{ inputs.CALLING_REPO || "muuvlabs-upptime/muuvlabs-upptime" }}
  STATUS_FILE_PATH: ${{ inputs.STATUS_FILE_PATH || "history/summary.json" }}

jobs:
  check_sites_status_and_notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout notifme
        uses: actions/checkout@v3
        with:
          repository: muuvlabs-upptime/muuvlabs-notifme
          path: main

      - name: Checkout upptime
        uses: actions/checkout@v3
        with:
          repository: ${{ env.CALLING_REPO }}
          path: calling-repo

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start
        working-directory: ./main
        run: |
          ls ../calling-repo
          npm ci
          npm run start
        env:
          STATUS_FILE_PATH: ../../calling-repo/${{ env.STATUS_FILE_PATH }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
